//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Serialization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public int JobOpeningId { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTimeOffset Duration { get; set; }
        public string Description { get; set; }
        public bool Completed { get; set; }
        public int ContactId { get; set; }
    
        public virtual JobOpening JobOpening { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
