//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Serialization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.JobOpenings = new HashSet<JobOpening>();
            this.Activities = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public string Organization { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<JobOpening> JobOpenings { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
