//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.Serialization
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOpeningPerson
    {
        public int JobOpeningId { get; set; }
        public int PersonId { get; set; }
        public int Type { get; set; }
    
        public virtual JobOpening JobOpening { get; set; }
        public virtual Person Person { get; set; }
    }
}
